Repository boostcampwm-2024/web24-GOMZ, pull requests merged in 2024-11, with the labels that each got.

#2 feat: 프로젝트 디렉토리 설정 완료
  .github/workflows/lint-and-prettier.yml
  .gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  eslint.config.js
  package-lock.json
  package.json
  server/package.json
Labels: 공통

#78 <Common> 중복되는 프로젝트 설정 제거
  .gitignore
  package-lock.json
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/package.json
  server/src/signaling-server/signaling-server.gateway.ts
  server/test/app.e2e-spec.ts
Labels: 공통, hotfix

#86 <FE> 스타일 라이브러리 설정
  .prettierrc
  client/package.json
  client/postcss.config.js
  client/src/index.css
  client/src/main.tsx
  client/tailwind.config.js
  package-lock.json
  package.json
Labels: FE

#87 <FE> 테스팅 환경 설정
  client/package.json
  client/vite.config.ts
  package-lock.json
Labels: FE

#89 <FE> client 폴더 ESLint 설정 문제 해결
  client/eslint.config.js
  eslint.config.js
Labels: FE, hotfix

#85 feat: github actions CD 스크립트 작성
  .github/workflows/cd-be.yml
Labels: BE

#97 <BE> 시그널링 서버 테스트 코드 작성
  package-lock.json
  server/package.json
  server/src/signaling-server/signaling-server.module.ts
  server/test/app.e2e-spec.ts
Labels: BE

#113 <BE> 데이터베이스 설정을 완료한다.
  package-lock.json
  server/package.json
  server/src/app.module.ts
Labels: BE

#114 <FE> 뒤로가기 버튼으로 StudyRoom 퇴장하기 구현
  client/src/components/StudyRoom/StudyRoom.tsx
Labels: FE

#123 <BE> 랜덤 닉네임 CORS 에러 수정
  server/src/main.ts
Labels: BE, hotfix

#129 <BE> StudyRoomRepository 경로 오류 수정
  server/src/study-room/study-room.module.ts
Labels: BE

#138 <FE> client 폴더 빌드 에러 수정
  client/src/components/Demo.tsx
Labels: FE, hotfix

#140 <BE> signalling-server에서 JSON이 아닌 Object를 보내는 현상
  server/src/signaling-server/signaling-server.gateway.ts
Labels: BE, hotfix

#143 <FE> signalingClient 연결 오류 수정
  client/src/socket/signalingClient.ts
Labels: FE, hotfix

#148 <BE> joinRoom 자신 제외 안되는 버그 수정
  server/src/signaling-server/signaling-server.gateway.ts
Labels: BE, hotfix

#152 <BE> 시그널링 소켓 joinRoom 안하고 연결해제하면 발생하는 오류 수정
  server/src/signaling-server/signaling-server.gateway.ts
Labels: BE, hotfix

#154 <BE> 랜덤 닉네임 종류 추가
  server/src/util/nicknameGenerator.ts
Labels: BE

#155 <FE> 피어 연결 과정에서 비동기 작업으로 인한 오류 수정
  client/src/socket/signalingClient.ts
Labels: FE, hotfix

#156 <FE> 하루 누적 공부 시간 저장 구현
  client/src/components/StudyRoom/StudyRoom.tsx
  client/src/components/StudyRoom/StudyRoomHeader.tsx
  client/src/components/StudyRoomList/Header.tsx
  client/src/components/StudyRoomList/index.tsx
Labels: FE

#158 <BE> sendMessage 시, 다른 클라이언트에서 message가 안 오는 현상 수정
  server/src/chatting-server/chatting-server.gateway.ts
Labels: BE, hotfix

#161 <BE> 시그널링 서버 joinRoom e2e 테스트 코드 작성
  server/test/app.e2e-spec.ts
Labels: BE

#167 <FE> 카메라를 키면 비디오 트랙이 추가되고, 끄면 제거되도록 개선
  client/src/components/StudyRoom/ControlBar.tsx
  client/src/hooks/useWebRTC.ts
  client/src/socket/signalingClient.ts
Labels: FE

#169 <BE> 방 리스트 api 수정
  server/src/study-room/repository/study-room.repository.ts
  server/src/study-room/study-room.service.ts
Labels: BE, hotfix

#171 <BE> iceCandidate를 candidate로 수정
  server/src/signaling-server/signaling-server.dto.ts
  server/src/signaling-server/signaling-server.gateway.ts
  server/test/app.e2e-spec.ts
Labels: BE, hotfix

#196 <FE> 스톱워치 애니메이션 온 ・ 오프 추가
  client/src/components/StudyRoom/StudyRoomHeader.tsx
  client/src/components/StudyRoom/VideoOverlay.tsx
  client/src/components/StudyRoomList/Header.tsx
  client/src/components/common/StopWatch.tsx
Labels: FE, hotfix

#197 <FE> 디바이스없이 방 입장 시 오류 해결
  client/src/hooks/useWebRTC.ts
Labels: FE

#201 <FE> 사용 가능한 디바이스가 없는 사용자와의 연결이 완전하도록 수정
  client/src/hooks/useWebRTC.ts
Labels: FE, hotfix

#204 <FE> 카메라가 켜지지 않는 오류 수정
  client/src/hooks/useWebRTC.ts
Labels: FE, hotfix

#205 <BE> STUN, TURN 서버 인증정보 발급 API 구현
  server/src/study-room/study-room.controller.ts
Labels: BE

#213 <FE> 공부방에서 뒤로가기를 한 번해도 나갈 수 있도록 수정
  client/src/components/StudyRoomList/ItemCard.tsx
Labels: FE, hotfix

#216 <Common> README 업데이트
  README.md
Labels: 공통

#214 <FE> /socket.io 경로로 지속적으로 HTTP 요청을 보내는 문제 해결
  client/src/hooks/useWebRTC.ts
  client/src/socket/signalingClient.ts
Labels: FE, hotfix
