Repository boostcampwm-2024/web24-GOMZ, pull requests merged in 2024-12, with the labels that each got.

#219 <BE> SFU 서버 구현
  package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/sfu-server/sfu-server.gateway.spec.ts
  server/src/sfu-server/sfu-server.gateway.ts
  server/src/sfu-server/sfu-server.module.ts
  server/src/sfu-server/sfu-server.service.ts
Labels: BE

#226 <FE> PeerConnection 메모리 누수 문제 해결
  client/src/socket/signalingClient.ts
Labels: FE, hotfix

#228 <BE> mesh namespace 설정 및 중복된 sfuServerModule 삭제
  server/src/app.module.ts
  server/src/signaling-server/signaling-server.gateway.ts
Labels: BE, hotfix

#230 <FE> 소켓 접속 시 signaling server url 뒤에 /mesh 추가
  client/src/stores/useWebRTCStore.ts
Labels: FE, hotfix

#222 <BE> 최대 인원 초과 방 접근 제한
  server/src/study-room/study-room.service.ts
Labels: BE

#234 <BE> SFU 방은 방을 나가도 삭제 타이머가 돌지 않도록 수정
  server/src/sfu-server/sfu-server.service.ts
Labels: BE, hotfix

#237 <BE> 존재하지 않는 study-room 입장 요청 시, 새로운 테스트방이 생성되는 버그 수정
  server/src/study-room/study-room.service.ts
Labels: BE, hotfix

#240 <BE> 구글 stun 서버 주소 제거
  server/src/study-room/study-room.controller.ts
Labels: BE
